language: csharp
sudo: required
dist: trusty
mono: latest

addons:
  apt:
    packages: 
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8

before_script:
 - chmod +x build.sh
script:
  - ./build.sh