# Version for the build. We make it clear that it's
# Appveyor as this isn't a version we expect to make
init:
- cmd: "set appVeyorBuildVersion=%appveyor_build_version%\necho appVeyorBuildVersion:%appVeyorBuildVersion% \n\nset branch=%APPVEYOR_REPO_BRANCH%\necho branch:%branch%\n\nset gitVersion=%branch:~-3%\necho gitversion:%gitVersion%\n\nset newVersion=%gitVersion%.%APPVEYOR_BUILD_NUMBER%\necho %newVersion%\n\n"
- cmd: appveyor UpdateBuild -Version "%newVersion%"

image: Visual Studio 2017

dotnet_csproj:
  patch: true
  file: 'commercetools.NETStandard\commercetools.NETStandard.csproj'
  version: '{version}'
  package_version: '{version}'
  
branches:
  only:
    - master

# Perform the build.
build_script:
  - dotnet --info
  - dotnet restore
  - dotnet build

# The tests are run as part of the build.
test: off