# Version for the build. We make it clear that it's
# Appveyor as this isn't a version we expect to make

version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
image: Visual Studio 2017
build_script:
  - ps: .\build.ps1
artifacts:
  - path: 'artifacts\**\*.nupkg'
    name: NuGet
# The tests are run as part of the build.
test: off
deploy:
- provider: NuGet
  server: https://www.myget.org/F/albellicommercetools/api/v2/package
  api_key:
    secure: /HKkSQf1V+dbHBovGgKEsscyFySUR7RJFrZ3iri/dgJY/HiUmva3FwuEF0Jqj/HQ
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: XYIxs6Rtb8KcG0alCgFV0CI2sF4E+w0fYas1Tvqu57EcTDmotvZksEeL0sh+Z59m
  on:
    branch: master
    appveyor_repo_tag: true