# Version for the build. We make it clear that it's
# Appveyor as this isn't a version we expect to make

version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
install:
  - ps: >-
      $displayVersion = (gitversion /showVariable FullSemVer);Try{Update-AppveyorBuild -Version $displayVersion;}Catch{Update-AppveyorBuild -Version "$displayVersion-$env:APPVEYOR_BUILD_NUMBER";}
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: 'src\commercetools.NETStandard\commercetools.NETStandard.csproj'
  version: '{version}'
  package_version: '{version}'
build_script:
  - ps: .\build.ps1
after_build:
 # - dotnet test ./commercetools.Test/commercetools.Test.csproj
  - ps: >-
      If ($env:APPVEYOR_REPO_TAG -eq $true) {
        dotnet pack ./commercetools.NETStandard/commercetools.NETStandard.csproj -c Release
      }
artifacts:
  - path: 'artifacts\**\*.nupkg'
    name: NuGet
# The tests are run as part of the build.
test: off
deploy:
- provider: NuGet
  server: https://www.myget.org/F/albellicommercetools/api/v2/package
  api_key:
    secure: /HKkSQf1V+dbHBovGgKEsscyFySUR7RJFrZ3iri/dgJY/HiUmva3FwuEF0Jqj/HQ
  skip_symbols: true
  on:
    branch: master